version: "3.7"

services:
  mysql:
    command: "--secure-file-priv=/tmp"
    image: mysql:latest
    restart: always
    environment:
      - "MYSQL_DATABASE=challenge_keys"
      - "MYSQL_USER=ms-pix-challenge"
      - "MYSQL_PASSWORD=123456"
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "13306:3306"
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - pixnet

  sonarqube:
    image: sonarqube
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - "sonar.jdbc.url=jdbc:postgresql://db:5432/sonar"
      - "sonar.jdbc.username=sonar"
      - "sonar.jdbc.password=sonar"
    volumes:
      - 'sonarqube_conf:/opt/sonarqube/conf'
      - 'sonarqube_data:/opt/sonarqube/data'
      - 'sonarqube_extensions:/opt/sonarqube/extensions'
      - 'sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins'
    networks:
      - pixnet

  db:
    image: postgres
    environment:
      - "POSTGRES_USER=sonar"
      - "POSTGRES_PASSWORD=sonar"
    volumes:
      - 'postgresql:/var/lib/postgresql'
      - 'postgresql_data:/var/lib/postgresql/data'
    networks:
      - pixnet

networks:
  pixnet:

volumes:
  mysql:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: