spring:
  application:
    name: pix-challenge

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/challenge_keys
    username: ms-pix-challenge
    password: 123456
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true

